<h1>This is shim</h1>

<script type="text/javascript">
    require(['exampleLib'], function(exampleLib) {
        console.log('exampleLib loaded:', exampleLib);
        exampleLib.someFunction();
    });
</script>

<!-- Deps start here -->
<script type="text/javascript">
    require(['DependencyOne'], function(DependencyOne) {
        console.log(DependencyOne.name);
    });
    require(['DependencyTwo'], function(DependencyTwo) {
        console.log(DependencyTwo.name);
    });
    require(['DepsMain'], function(DepsMain) {
        DepsMain.init(); // Initialize the module
    });
</script>
